/* board-design/v2 统一数据源：总览页与个人页同源渲染。
 * 全部为设计示意数据（非真实当前任务）。字段名为真实字段名。
 * sec: doing=进行中 blocked=阻塞 wait=等待中 decide=待老板决定 done=已完成（本轮）
 */
const BOARD = {
  version: "board-design/v2",
  members: [
    { key:"bi", name:"笔", login:"xst-bi", role:"产品 UI / 视觉与品牌负责人", tasks:[
      { id:"mz-ph-ui/team-board/design-first/current-multitask-20261004", main:true, sec:"doing",
        title:"团队看板设计先行 v2（总览＋个人页模板）", status:"实施中", scls:"p-impl",
        goal:{url:"https://github.com/xiaoshutong-ai/mz-ph-ui/pull/63", note:"载体，不新建 Goal"},
        scope:"范围：总览＋可复用个人页设计产物 v2；AC：两页可交互对照一致，示意数据显式标示",
        owr:"owner: EmilioJI ／ writer: xst-bi（本轮唯一） ／ reviewer: 待独立角色审查",
        stage:"stage: 设计中 ／ activity: 原型 v2＋渲染验证",
        repo:"repo: mz-ph-ui ／ PR: #63 ／ head: 9ab8843（merge，已合入；不代表验收）",
        evidence:"board-design/v2 原型文件＋渲染截图",
        result:"result: 原型 v2 完成", next:"下一步：交老板审阅 v2 → 匣协调生产实现",
        deps:"依赖：匣补真实状态源字段", blocker:"无", priority:"已批准 · 高",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 21:50 CST" },
      { id:"demo-bi-002", sec:"doing",
        title:"夫子三页视觉评审收尾", status:"实施中", scls:"p-impl",
        goal:{url:"https://github.com/xiaoshutong-ai/xiaoshutong-fuzipartner/issues/20", note:""},
        scope:"范围：三页母版＋冻结合同视觉评审",
        owr:"owner: EmilioJI ／ writer: xst-bi ／ reviewer: —",
        stage:"stage: 评审中 ／ activity: 合同复核",
        repo:"repo: xiaoshutong-design-lab ／ PR: #4 ／ head: be5fb49",
        evidence:"issue #20 评论（已发）",
        result:"result: MUST_FIX 已关闭", next:"下一步：等老板三项产品决策",
        deps:"—", blocker:"无", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 20:57 CST" },
      { id:"demo-bi-003", sec:"decide",
        title:"夫子三项产品决策（头像入口／反馈跳转／字体策略）", status:"待老板决定", scls:"p-decide",
        goal:{url:"https://github.com/xiaoshutong-ai/xiaoshutong-fuzipartner/issues/20", note:""},
        scope:"范围：三项产品选择（仅建议，不代决定）",
        owr:"owner: EmilioJI（待定夺） ／ writer: — ／ reviewer: —",
        stage:"stage: 等待决策 ／ activity: —",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：老板定夺后进入 Android 实现",
        deps:"老板决策", blocker:"待老板决定（非阻塞设计）", priority:"待定",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 18:00 CST" },
      { id:"demo-bi-004", sec:"done",
        title:"Goal #28 团队 Skill v0.4.0 落地", status:"已完成", scls:"p-done",
        goal:{url:"https://github.com/xiaoshutong-ai/xiaoshutong-governance/issues/28", note:""},
        scope:"范围：Skill 安装＋冒烟",
        owr:"owner: EmilioJI ／ writer: xst-bi ／ reviewer: xst-yan（独立评审）",
        stage:"stage: 已交付 ／ activity: —",
        repo:"repo: xiaoshutong-governance ／ commit: 875e52c",
        evidence:"issue #28 评论（已发）",
        result:"result: ROLLOUT_PASS", next:"—",
        deps:"—", blocker:"—", priority:"已批准 · 高",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 19:34 CST" }
    ]},
    { key:"mo", name:"墨", login:"xst-mo", role:"平台工程（核心产品/共享组件）", tasks:[
      { id:"demo-mo-001", main:true, sec:"doing",
        title:"共享组件 capability 缺口补齐（设计示意）", status:"实施中", scls:"p-impl",
        goal:{url:"", note:"示意"},
        scope:"范围：共享组件（示意）",
        owr:"owner: EmilioJI ／ writer: xst-mo ／ reviewer: —",
        stage:"stage: 实施中 ／ activity: 编码",
        repo:"repo:（示意）", evidence:"—", result:"—",
        next:"下一步：（示意）", deps:"—", blocker:"无", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 17:20 CST" },
      { id:"demo-mo-002", sec:"wait",
        title:"核心仓 CI 绿色守护", status:"等待", scls:"p-wait", tag:["等待 runner","st-stale"],
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-mo",
        stage:"stage: 等待 ／ activity: 等 runner",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：runner 就绪后重跑", deps:"CI runner", blocker:"等待 runner（有过期风险）", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 09:12 CST" }
    ]},
    { key:"zhi", name:"纸", login:"xst-zhi", role:"产品工程 · 生态仓组 A", tasks:[
      { id:"demo-zhi-001", main:true, sec:"doing",
        title:"夫子三页合同 MUST_FIX 修复", status:"实施中", scls:"p-impl",
        goal:{url:"https://github.com/xiaoshutong-ai/xiaoshutong-fuzipartner/issues/20", note:""},
        scope:"范围：三份合同引用修正",
        owr:"writer: xst-zhi",
        stage:"stage: 实施中 ／ activity: 文档修正",
        repo:"repo: xiaoshutong-design-lab ／ PR: #4",
        evidence:"PR 评论（示意）",
        result:"—", next:"下一步：等复核",
        deps:"—", blocker:"无", priority:"已批准 · 高",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 19:05 CST" },
      { id:"demo-zhi-002", sec:"doing",
        title:"A 组仓日常巡检（设计示意）", status:"实施中", scls:"p-impl",
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-zhi",
        stage:"stage: 实施中",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：（示意）", deps:"—", blocker:"无", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 18:30 CST" },
      { id:"demo-zhi-003", sec:"done",
        title:"视觉交付清单 v1", status:"已完成", scls:"p-done",
        goal:{url:"https://github.com/xiaoshutong-ai/xiaoshutong-fuzipartner/issues/20", note:""},
        scope:"范围：三页交付清单",
        owr:"writer: xst-zhi",
        stage:"stage: 已交付 ／ activity: —",
        repo:"—", evidence:"issue 评论 5974297142",
        result:"result: 已交付", next:"—",
        deps:"—", blocker:"—", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-03 22:47 CST" }
    ]},
    { key:"yan", name:"砚", login:"xst-yan", role:"架构评审 · 质量与安全", tasks:[
      { id:"demo-yan-001", main:true, sec:"wait",
        title:"团队 Skill v0.4 独立评审排期（设计示意）", status:"等待", scls:"p-wait",
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"reviewer: xst-yan",
        stage:"stage: 等待 ／ activity: 排期",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：确定评审窗口", deps:"评审排期", blocker:"无", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 15:30 CST" },
      { id:"demo-yan-002", sec:"decide",
        title:"周五质量周报口径", status:"待老板决定", scls:"p-decide",
        goal:{url:"", note:"示意"},
        scope:"范围：周报口径确认",
        owr:"owner: EmilioJI（待定夺）",
        stage:"stage: 等待决策 ／ activity: —",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：老板确认口径", deps:"老板决策", blocker:"待老板决定", priority:"待定",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 12:00 CST" }
    ]},
    { key:"juan", name:"卷", login:"xst-juan", role:"产品工程 · 生态仓组 B", tasks:[
      { id:"demo-juan-001", main:true, sec:"blocked",
        title:"B 组仓发布前检查（设计示意）", status:"阻塞", scls:"p-blocked", tag:["阻塞","st-blocked"],
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-juan",
        stage:"stage: 阻塞 ／ activity: 等待权限",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：权限到位后继续", deps:"CI 写权限", blocker:"缺 CI 写权限，已交匣协调", priority:"已批准 · 高",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 16:12 CST" },
      { id:"demo-juan-002", sec:"blocked",
        title:"B 组仓日常巡检（设计示意）", status:"权限不足", scls:"p-wait", tag:["权限不足","st-noperm"],
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-juan",
        stage:"stage: 受阻 ／ activity: 只读巡检",
        repo:"—", evidence:"只读巡检记录",
        result:"—", next:"下一步：等写权限",
        deps:"仓库读权限（已有）／写权限（缺）", blocker:"写权限不足：仅只读", priority:"已批准 · 低",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 16:12 CST" }
    ]},
    { key:"xia", name:"匣", login:"xst-xia", role:"Orchestrator ＋ Integrator", tasks:[
      { id:"demo-xia-001", main:true, sec:"doing",
        title:"看板生产实现协调（设计示意）", status:"实施中", scls:"p-impl",
        goal:{url:"https://github.com/xiaoshutong-ai/mz-ph-ui/pull/63", note:""},
        scope:"范围：生产实现协调",
        owr:"owner: EmilioJI ／ writer: xst-xia（生产实现）",
        stage:"stage: 实施中 ／ activity: 协调",
        repo:"repo: mz-ph-ui ／ PR: #63",
        evidence:"—", result:"—",
        next:"下一步：按设计产物实施", deps:"设计产物（本轮）", blocker:"无", priority:"已批准 · 高",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 20:15 CST" },
      { id:"demo-xia-002", sec:"doing",
        title:"PR 合入与 Gate 检查（设计示意）", status:"实施中", scls:"p-impl",
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-xia",
        stage:"stage: 实施中",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：（示意）", deps:"—", blocker:"无", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 19:40 CST" },
      { id:"demo-xia-003", sec:"wait",
        title:"5070TI 设备排期", status:"未接入", scls:"p-wait", tag:["未接入","st-unconn"],
        goal:{url:"", note:"示意"},
        scope:"范围：设备排期",
        owr:"writer: xst-xia",
        stage:"stage: 未接入 ／ activity: —",
        repo:"—", evidence:"—", result:"—",
        next:"下一步：设备上线后安排", deps:"5070TI 设备", blocker:"设备未接入", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"—" },
      { id:"demo-xia-004", sec:"done",
        title:"日报汇总", status:"已完成", scls:"p-done",
        goal:{url:"", note:"示意"},
        scope:"范围：（示意）",
        owr:"writer: xst-xia",
        stage:"stage: 已交付 ／ activity: —",
        repo:"—", evidence:"—",
        result:"result: 已交付", next:"—",
        deps:"—", blocker:"—", priority:"已批准 · 中",
        checked:"2026-10-04 22:00 CST", updated:"2026-10-04 20:15 CST" }
    ]}
  ]
};
